import { Key } from "react";

export enum Rarity {
  commune = "commune",
  peuCommune = "peu commune",
  rare = "rare",
  doubleRare = "double rare",
  ultraRare = "ultra rare",
  illustrationRare = "illustration rare",
  illustrationSpecialeRare = "illustration spéciale rare",
  hyperRare = "hyper rare",
}

export enum Type {
  normal = "normal",
  reverse = "reverse",
  holo = "holo",
  secret = "secret",
}

export type Card = {
  name: string;
  type: Type;
  rarity: Rarity;
  id: Key;
  hasReverseVersion?: true;
};

export const all_cards_flat: Card[] = [
  {
    id: "1",
    type: Type.normal,
    name: "Bulbizarre",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "1_r",
    type: Type.reverse,
    name: "Bulbizarre",
    rarity: Rarity.commune,
  },
  {
    id: "2",
    type: Type.normal,
    name: "Herbizarre",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "2_r",
    type: Type.reverse,
    name: "Herbizarre",
    rarity: Rarity.peuCommune,
  },
  {
    id: "3",
    type: Type.holo,
    name: "Florizarre-ex",
    rarity: Rarity.doubleRare,
  },
  {
    id: "4",
    type: Type.normal,
    name: "Salamèche",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "4_r",
    type: Type.reverse,
    name: "Salamèche",
    rarity: Rarity.commune,
  },
  {
    id: "5",
    type: Type.normal,
    name: "Reptincel",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "5_r",
    type: Type.reverse,
    name: "Reptincel",
    rarity: Rarity.peuCommune,
  },
  {
    id: "6",
    type: Type.holo,
    name: "Dracaufeu-ex",
    rarity: Rarity.doubleRare,
  },
  {
    id: "7",
    type: Type.normal,
    name: "Carapuce",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "7_r",
    type: Type.reverse,
    name: "Carapuce",
    rarity: Rarity.commune,
  },
  {
    id: "8",
    type: Type.normal,
    name: "Carabaffe",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "8_r",
    type: Type.reverse,
    name: "Carabaffe",
    rarity: Rarity.peuCommune,
  },
  {
    id: "9",
    type: Type.holo,
    name: "Tortank-ex",
    rarity: Rarity.doubleRare,
  },
  {
    id: "10",
    type: Type.normal,
    name: "Chenipan",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "10_r",
    type: Type.reverse,
    name: "Chenipan",
    rarity: Rarity.commune,
  },
  {
    id: "11",
    type: Type.normal,
    name: "Chrysacier",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "11_r",
    type: Type.reverse,
    name: "Chrysacier",
    rarity: Rarity.commune,
  },
  {
    id: "12",
    type: Type.normal,
    name: "Papilusion",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "12_r",
    type: Type.reverse,
    name: "Papilusion",
    rarity: Rarity.peuCommune,
  },
  {
    id: "13",
    type: Type.normal,
    name: "Aspicot",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "13_r",
    type: Type.reverse,
    name: "Aspicot",
    rarity: Rarity.commune,
  },
  {
    id: "14",
    type: Type.normal,
    name: "Coconfort",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "14_r",
    type: Type.reverse,
    name: "Coconfort",
    rarity: Rarity.commune,
  },
  {
    id: "15",
    type: Type.normal,
    name: "Dardargnan",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "15_r",
    type: Type.reverse,
    name: "Dardargnan",
    rarity: Rarity.rare,
  },
  {
    id: "16",
    type: Type.normal,
    name: "Roucool",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "16_r",
    type: Type.reverse,
    name: "Roucool",
    rarity: Rarity.commune,
  },
  {
    id: "17",
    type: Type.normal,
    name: "Roucoups",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "17_r",
    type: Type.reverse,
    name: "Roucoups",
    rarity: Rarity.commune,
  },
  {
    id: "18",
    type: Type.normal,
    name: "Roucarnage",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "18_r",
    type: Type.reverse,
    name: "Roucarnage",
    rarity: Rarity.peuCommune,
  },
  {
    id: "19",
    type: Type.normal,
    name: "Rattata",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "19_r",
    type: Type.reverse,
    name: "Rattata",
    rarity: Rarity.commune,
  },
  {
    id: "20",
    type: Type.normal,
    name: "Rattatac",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "20_r",
    type: Type.reverse,
    name: "Rattatac",
    rarity: Rarity.peuCommune,
  },
  {
    id: "21",
    type: Type.normal,
    name: "Piafabec",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "21_r",
    type: Type.reverse,
    name: "Piafabec",
    rarity: Rarity.commune,
  },
  {
    id: "22",
    type: Type.normal,
    name: "Rapasdepic",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "22_r",
    type: Type.reverse,
    name: "Rapasdepic",
    rarity: Rarity.peuCommune,
  },
  {
    id: "23",
    type: Type.normal,
    name: "Abo",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "23_r",
    type: Type.reverse,
    name: "Abo",
    rarity: Rarity.commune,
  },
  {
    id: "24",
    type: Type.holo,
    name: "Arbok-ex",
    rarity: Rarity.doubleRare,
  },
  {
    id: "25",
    type: Type.normal,
    name: "Pikachu",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "25_r",
    type: Type.reverse,
    name: "Pikachu",
    rarity: Rarity.commune,
  },
  {
    id: "26",
    type: Type.normal,
    name: "Raichu",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "26_r",
    type: Type.reverse,
    name: "Raichu",
    rarity: Rarity.rare,
  },
  {
    id: "27",
    type: Type.normal,
    name: "Sabelette",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "27_r",
    type: Type.reverse,
    name: "Sabelette",
    rarity: Rarity.commune,
  },
  {
    id: "28",
    type: Type.normal,
    name: "Sablaireau",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "28_r",
    type: Type.reverse,
    name: "Sablaireau",
    rarity: Rarity.peuCommune,
  },
  {
    id: "29",
    type: Type.normal,
    name: "Nidoran♀",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "29_r",
    type: Type.reverse,
    name: "Nidoran♀",
    rarity: Rarity.commune,
  },
  {
    id: "30",
    type: Type.normal,
    name: "Nidorina",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "30_r",
    type: Type.reverse,
    name: "Nidorina",
    rarity: Rarity.peuCommune,
  },
  {
    id: "31",
    type: Type.normal,
    name: "Nidoqueen",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "31_r",
    type: Type.reverse,
    name: "Nidoqueen",
    rarity: Rarity.peuCommune,
  },
  {
    id: "32",
    type: Type.normal,
    name: "Nidoran♂",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "32_r",
    type: Type.reverse,
    name: "Nidoran♂",
    rarity: Rarity.commune,
  },
  {
    id: "33",
    type: Type.normal,
    name: "Nidorino",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "33_r",
    type: Type.reverse,
    name: "Nidorino",
    rarity: Rarity.peuCommune,
  },
  {
    id: "34",
    type: Type.normal,
    name: "Nidoking",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "34_r",
    type: Type.reverse,
    name: "Nidoking",
    rarity: Rarity.rare,
  },
  {
    id: "35",
    type: Type.normal,
    name: "Mélofée",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "35_r",
    type: Type.reverse,
    name: "Mélofée",
    rarity: Rarity.commune,
  },
  {
    id: "36",
    type: Type.normal,
    name: "Mélodelfe",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "36_r",
    type: Type.reverse,
    name: "Mélodelfe",
    rarity: Rarity.peuCommune,
  },
  {
    id: "37",
    type: Type.normal,
    name: "Goupix",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "37_r",
    type: Type.reverse,
    name: "Goupix",
    rarity: Rarity.commune,
  },
  {
    id: "38",
    type: Type.holo,
    name: "Feunard-ex",
    rarity: Rarity.doubleRare,
  },
  {
    id: "39",
    type: Type.normal,
    name: "Rondoudou",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "39_r",
    type: Type.reverse,
    name: "Rondoudou",
    rarity: Rarity.commune,
  },
  {
    id: "40",
    type: Type.holo,
    name: "Grodoudou-ex",
    rarity: Rarity.doubleRare,
  },
  {
    id: "41",
    type: Type.normal,
    name: "Nosferapti",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "41_r",
    type: Type.reverse,
    name: "Nosferapti",
    rarity: Rarity.commune,
  },
  {
    id: "42",
    type: Type.normal,
    name: "Nosferalto",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "42_r",
    type: Type.reverse,
    name: "Nosferalto",
    rarity: Rarity.peuCommune,
  },
  {
    id: "43",
    type: Type.normal,
    name: "Mystherbe",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "43_r",
    type: Type.reverse,
    name: "Mystherbe",
    rarity: Rarity.commune,
  },
  {
    id: "44",
    type: Type.normal,
    name: "Ortide",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "44_r",
    type: Type.reverse,
    name: "Ortide",
    rarity: Rarity.peuCommune,
  },
  {
    id: "45",
    type: Type.normal,
    name: "Rafflesia",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "45_r",
    type: Type.reverse,
    name: "Rafflesia",
    rarity: Rarity.rare,
  },
  {
    id: "46",
    type: Type.normal,
    name: "Paras",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "46_r",
    type: Type.reverse,
    name: "Paras",
    rarity: Rarity.commune,
  },
  {
    id: "47",
    type: Type.normal,
    name: "Parasect",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "47_r",
    type: Type.reverse,
    name: "Parasect",
    rarity: Rarity.peuCommune,
  },
  {
    id: "48",
    type: Type.normal,
    name: "Mimitoss",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "48_r",
    type: Type.reverse,
    name: "Mimitoss",
    rarity: Rarity.commune,
  },
  {
    id: "49",
    type: Type.normal,
    name: "Aéromite",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "49_r",
    type: Type.reverse,
    name: "Aéromite",
    rarity: Rarity.peuCommune,
  },
  {
    id: "50",
    type: Type.normal,
    name: "Taupiqueur",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "50_r",
    type: Type.reverse,
    name: "Taupiqueur",
    rarity: Rarity.commune,
  },
  {
    id: "51",
    type: Type.normal,
    name: "Triopikeur",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "51_r",
    type: Type.reverse,
    name: "Triopikeur",
    rarity: Rarity.peuCommune,
  },
  {
    id: "52",
    type: Type.normal,
    name: "Miaouss",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "52_r",
    type: Type.reverse,
    name: "Miaouss",
    rarity: Rarity.commune,
  },
  {
    id: "53",
    type: Type.normal,
    name: "Persian",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "53_r",
    type: Type.reverse,
    name: "Persian",
    rarity: Rarity.peuCommune,
  },
  {
    id: "54",
    type: Type.normal,
    name: "Psykokwak",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "54_r",
    type: Type.reverse,
    name: "Psykokwak",
    rarity: Rarity.commune,
  },
  {
    id: "55",
    type: Type.normal,
    name: "Akwakwak",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "55_r",
    type: Type.reverse,
    name: "Akwakwak",
    rarity: Rarity.peuCommune,
  },
  {
    id: "56",
    type: Type.normal,
    name: "Férosinge",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "56_r",
    type: Type.reverse,
    name: "Férosinge",
    rarity: Rarity.commune,
  },
  {
    id: "57",
    type: Type.normal,
    name: "Colossinge",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "57_r",
    type: Type.reverse,
    name: "Colossinge",
    rarity: Rarity.peuCommune,
  },
  {
    id: "58",
    type: Type.normal,
    name: "Caninos",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "58_r",
    type: Type.reverse,
    name: "Caninos",
    rarity: Rarity.commune,
  },
  {
    id: "59",
    type: Type.normal,
    name: "Arcanin",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "59_r",
    type: Type.reverse,
    name: "Arcanin",
    rarity: Rarity.peuCommune,
  },
  {
    id: "60",
    type: Type.normal,
    name: "Ptitard",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "60_r",
    type: Type.reverse,
    name: "Ptitard",
    rarity: Rarity.commune,
  },
  {
    id: "61",
    type: Type.normal,
    name: "Têtarte",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "61_r",
    type: Type.reverse,
    name: "Têtarte",
    rarity: Rarity.commune,
  },
  {
    id: "62",
    type: Type.normal,
    name: "Tartard",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "62_r",
    type: Type.reverse,
    name: "Tartard",
    rarity: Rarity.peuCommune,
  },
  {
    id: "63",
    type: Type.normal,
    name: "Abra",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "63_r",
    type: Type.reverse,
    name: "Abra",
    rarity: Rarity.commune,
  },
  {
    id: "64",
    type: Type.normal,
    name: "Kadabra",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "64_r",
    type: Type.reverse,
    name: "Kadabra",
    rarity: Rarity.peuCommune,
  },
  {
    id: "65",
    type: Type.holo,
    name: "Alakazam-ex",
    rarity: Rarity.doubleRare,
  },
  {
    id: "66",
    type: Type.normal,
    name: "Machoc",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "66_r",
    type: Type.reverse,
    name: "Machoc",
    rarity: Rarity.commune,
  },
  {
    id: "67",
    type: Type.normal,
    name: "Machopeur",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "67_r",
    type: Type.reverse,
    name: "Machopeur",
    rarity: Rarity.peuCommune,
  },
  {
    id: "68",
    type: Type.normal,
    name: "Mackogneur",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "68_r",
    type: Type.reverse,
    name: "Mackogneur",
    rarity: Rarity.rare,
  },
  {
    id: "69",
    type: Type.normal,
    name: "Chétiflor",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "69_r",
    type: Type.reverse,
    name: "Chétiflor",
    rarity: Rarity.commune,
  },
  {
    id: "70",
    type: Type.normal,
    name: "Boustiflor",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "70_r",
    type: Type.reverse,
    name: "Boustiflor",
    rarity: Rarity.commune,
  },
  {
    id: "71",
    type: Type.normal,
    name: "Empiflor",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "71_r",
    type: Type.reverse,
    name: "Empiflor",
    rarity: Rarity.peuCommune,
  },
  {
    id: "72",
    type: Type.normal,
    name: "Tentacool",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "72_r",
    type: Type.reverse,
    name: "Tentacool",
    rarity: Rarity.commune,
  },
  {
    id: "73",
    type: Type.normal,
    name: "Tentacruel",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "73_r",
    type: Type.reverse,
    name: "Tentacruel",
    rarity: Rarity.peuCommune,
  },
  {
    id: "74",
    type: Type.normal,
    name: "Racaillou",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "74_r",
    type: Type.reverse,
    name: "Racaillou",
    rarity: Rarity.commune,
  },
  {
    id: "75",
    type: Type.normal,
    name: "Gravalanch",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "75_r",
    type: Type.reverse,
    name: "Gravalanch",
    rarity: Rarity.peuCommune,
  },
  {
    id: "76",
    type: Type.holo,
    name: "Grolem-ex",
    rarity: Rarity.doubleRare,
  },
  {
    id: "77",
    type: Type.normal,
    name: "Ponyta",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "77_r",
    type: Type.reverse,
    name: "Ponyta",
    rarity: Rarity.commune,
  },
  {
    id: "78",
    type: Type.normal,
    name: "Galopa",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "78_r",
    type: Type.reverse,
    name: "Galopa",
    rarity: Rarity.peuCommune,
  },
  {
    id: "79",
    type: Type.normal,
    name: "Ramoloss",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "79_r",
    type: Type.reverse,
    name: "Ramoloss",
    rarity: Rarity.commune,
  },
  {
    id: "80",
    type: Type.normal,
    name: "Flagadoss",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "80_r",
    type: Type.reverse,
    name: "Flagadoss",
    rarity: Rarity.peuCommune,
  },
  {
    id: "81",
    type: Type.normal,
    name: "Magnéti",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "81_r",
    type: Type.reverse,
    name: "Magnéti",
    rarity: Rarity.commune,
  },
  {
    id: "82",
    type: Type.normal,
    name: "Magnéton",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "82_r",
    type: Type.reverse,
    name: "Magnéton",
    rarity: Rarity.peuCommune,
  },
  {
    id: "83",
    type: Type.normal,
    name: "Canarticho",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "83_r",
    type: Type.reverse,
    name: "Canarticho",
    rarity: Rarity.commune,
  },
  {
    id: "84",
    type: Type.normal,
    name: "Doduo",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "84_r",
    type: Type.reverse,
    name: "Doduo",
    rarity: Rarity.commune,
  },
  {
    id: "85",
    type: Type.normal,
    name: "Dodrio",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "85_r",
    type: Type.reverse,
    name: "Dodrio",
    rarity: Rarity.rare,
  },
  {
    id: "86",
    type: Type.normal,
    name: "Otaria",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "86_r",
    type: Type.reverse,
    name: "Otaria",
    rarity: Rarity.commune,
  },
  {
    id: "87",
    type: Type.normal,
    name: "Lamantine",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "87_r",
    type: Type.reverse,
    name: "Lamantine",
    rarity: Rarity.peuCommune,
  },
  {
    id: "88",
    type: Type.normal,
    name: "Tadmorv",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "88_r",
    type: Type.reverse,
    name: "Tadmorv",
    rarity: Rarity.commune,
  },
  {
    id: "89",
    type: Type.normal,
    name: "Grotadmorv",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "89_r",
    type: Type.reverse,
    name: "Grotadmorv",
    rarity: Rarity.peuCommune,
  },
  {
    id: "90",
    type: Type.normal,
    name: "Kokiyas",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "90_r",
    type: Type.reverse,
    name: "Kokiyas",
    rarity: Rarity.commune,
  },
  {
    id: "91",
    type: Type.normal,
    name: "Crustabri",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "91_r",
    type: Type.reverse,
    name: "Crustabri",
    rarity: Rarity.peuCommune,
  },
  {
    id: "92",
    type: Type.normal,
    name: "Fantominus",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "92_r",
    type: Type.reverse,
    name: "Fantominus",
    rarity: Rarity.commune,
  },
  {
    id: "93",
    type: Type.normal,
    name: "Spectrum",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "93_r",
    type: Type.reverse,
    name: "Spectrum",
    rarity: Rarity.peuCommune,
  },
  {
    id: "94",
    type: Type.normal,
    name: "Ectoplasma",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "94_r",
    type: Type.reverse,
    name: "Ectoplasma",
    rarity: Rarity.rare,
  },
  {
    id: "95",
    type: Type.normal,
    name: "Onix",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "95_r",
    type: Type.reverse,
    name: "Onix",
    rarity: Rarity.peuCommune,
  },
  {
    id: "96",
    type: Type.normal,
    name: "Soporifik",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "96_r",
    type: Type.reverse,
    name: "Soporifik",
    rarity: Rarity.commune,
  },
  {
    id: "97",
    type: Type.normal,
    name: "Hypnomade",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "97_r",
    type: Type.reverse,
    name: "Hypnomade",
    rarity: Rarity.peuCommune,
  },
  {
    id: "98",
    type: Type.normal,
    name: "Krabby",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "98_r",
    type: Type.reverse,
    name: "Krabby",
    rarity: Rarity.commune,
  },
  {
    id: "99",
    type: Type.normal,
    name: "Krabboss",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "99_r",
    type: Type.reverse,
    name: "Krabboss",
    rarity: Rarity.peuCommune,
  },
  {
    id: "100",
    type: Type.normal,
    name: "Voltorbe",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "100_r",
    type: Type.reverse,
    name: "Voltorbe",
    rarity: Rarity.commune,
  },
  {
    id: "101",
    type: Type.normal,
    name: "Électrode",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "101_r",
    type: Type.reverse,
    name: "Électrode",
    rarity: Rarity.rare,
  },
  {
    id: "102",
    type: Type.normal,
    name: "Noeunoeuf",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "102_r",
    type: Type.reverse,
    name: "Noeunoeuf",
    rarity: Rarity.commune,
  },
  {
    id: "103",
    type: Type.normal,
    name: "Noadkoko",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "103_r",
    type: Type.reverse,
    name: "Noadkoko",
    rarity: Rarity.peuCommune,
  },
  {
    id: "104",
    type: Type.normal,
    name: "Osselait",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "104_r",
    type: Type.reverse,
    name: "Osselait",
    rarity: Rarity.commune,
  },
  {
    id: "105",
    type: Type.normal,
    name: "Ossatueur",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "105_r",
    type: Type.reverse,
    name: "Ossatueur",
    rarity: Rarity.rare,
  },
  {
    id: "106",
    type: Type.normal,
    name: "Kicklee",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "106_r",
    type: Type.reverse,
    name: "Kicklee",
    rarity: Rarity.peuCommune,
  },
  {
    id: "107",
    type: Type.normal,
    name: "Tygnon",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "107_r",
    type: Type.reverse,
    name: "Tygnon",
    rarity: Rarity.peuCommune,
  },
  {
    id: "108",
    type: Type.normal,
    name: "Excelangue",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "108_r",
    type: Type.reverse,
    name: "Excelangue",
    rarity: Rarity.commune,
  },
  {
    id: "109",
    type: Type.normal,
    name: "Smogo",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "109_r",
    type: Type.reverse,
    name: "Smogo",
    rarity: Rarity.commune,
  },
  {
    id: "110",
    type: Type.normal,
    name: "Smogogo",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "110_r",
    type: Type.reverse,
    name: "Smogogo",
    rarity: Rarity.rare,
  },
  {
    id: "111",
    type: Type.normal,
    name: "Rhinocorne",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "111_r",
    type: Type.reverse,
    name: "Rhinocorne",
    rarity: Rarity.commune,
  },
  {
    id: "112",
    type: Type.normal,
    name: "Rhinoféros",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "112_r",
    type: Type.reverse,
    name: "Rhinoféros",
    rarity: Rarity.peuCommune,
  },
  {
    id: "113",
    type: Type.normal,
    name: "Leveinard",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "113_r",
    type: Type.reverse,
    name: "Leveinard",
    rarity: Rarity.rare,
  },
  {
    id: "114",
    type: Type.normal,
    name: "Saquedeneu",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "114_r",
    type: Type.reverse,
    name: "Saquedeneu",
    rarity: Rarity.commune,
  },
  {
    id: "115",
    type: Type.holo,
    name: "Kangourex-ex",
    rarity: Rarity.doubleRare,
  },
  {
    id: "116",
    type: Type.normal,
    name: "Hypotrempe",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "116_r",
    type: Type.reverse,
    name: "Hypotrempe",
    rarity: Rarity.commune,
  },
  {
    id: "117",
    type: Type.normal,
    name: "Hypocéan",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "117_r",
    type: Type.reverse,
    name: "Hypocéan",
    rarity: Rarity.peuCommune,
  },
  {
    id: "118",
    type: Type.normal,
    name: "Poissirène",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "118_r",
    type: Type.reverse,
    name: "Poissirène",
    rarity: Rarity.commune,
  },
  {
    id: "119",
    type: Type.normal,
    name: "Poissoroy",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "119_r",
    type: Type.reverse,
    name: "Poissoroy",
    rarity: Rarity.peuCommune,
  },
  {
    id: "120",
    type: Type.normal,
    name: "Stari",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "120_r",
    type: Type.reverse,
    name: "Stari",
    rarity: Rarity.commune,
  },
  {
    id: "121",
    type: Type.normal,
    name: "Staross",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "121_r",
    type: Type.reverse,
    name: "Staross",
    rarity: Rarity.rare,
  },
  {
    id: "122",
    type: Type.normal,
    name: "M. Mime",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "122_r",
    type: Type.reverse,
    name: "M. Mime",
    rarity: Rarity.rare,
  },
  {
    id: "123",
    type: Type.normal,
    name: "Insécateur",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "123_r",
    type: Type.reverse,
    name: "Insécateur",
    rarity: Rarity.peuCommune,
  },
  {
    id: "124",
    type: Type.holo,
    name: "Lippoutou-ex",
    rarity: Rarity.doubleRare,
  },
  {
    id: "125",
    type: Type.normal,
    name: "Élektek",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "125_r",
    type: Type.reverse,
    name: "Élektek",
    rarity: Rarity.commune,
  },
  {
    id: "126",
    type: Type.normal,
    name: "Magmar",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "126_r",
    type: Type.reverse,
    name: "Magmar",
    rarity: Rarity.commune,
  },
  {
    id: "127",
    type: Type.normal,
    name: "Scarabrute",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "127_r",
    type: Type.reverse,
    name: "Scarabrute",
    rarity: Rarity.peuCommune,
  },
  {
    id: "128",
    type: Type.normal,
    name: "Tauros",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "128_r",
    type: Type.reverse,
    name: "Tauros",
    rarity: Rarity.peuCommune,
  },
  {
    id: "129",
    type: Type.normal,
    name: "Magicarpe",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "129_r",
    type: Type.reverse,
    name: "Magicarpe",
    rarity: Rarity.commune,
  },
  {
    id: "130",
    type: Type.normal,
    name: "Léviator",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "130_r",
    type: Type.reverse,
    name: "Léviator",
    rarity: Rarity.rare,
  },
  {
    id: "131",
    type: Type.normal,
    name: "Lokhlass",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "131_r",
    type: Type.reverse,
    name: "Lokhlass",
    rarity: Rarity.peuCommune,
  },
  {
    id: "132",
    type: Type.normal,
    name: "Métamorph",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "132_r",
    type: Type.reverse,
    name: "Métamorph",
    rarity: Rarity.rare,
  },
  {
    id: "133",
    type: Type.normal,
    name: "Évoli",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "133_r",
    type: Type.reverse,
    name: "Évoli",
    rarity: Rarity.commune,
  },
  {
    id: "134",
    type: Type.normal,
    name: "Aquali",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "134_r",
    type: Type.reverse,
    name: "Aquali",
    rarity: Rarity.rare,
  },
  {
    id: "135",
    type: Type.normal,
    name: "Voltali",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "135_r",
    type: Type.reverse,
    name: "Voltali",
    rarity: Rarity.rare,
  },
  {
    id: "136",
    type: Type.normal,
    name: "Pyroli",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "136_r",
    type: Type.reverse,
    name: "Pyroli",
    rarity: Rarity.rare,
  },
  {
    id: "137",
    type: Type.normal,
    name: "Porygon",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "137_r",
    type: Type.reverse,
    name: "Porygon",
    rarity: Rarity.commune,
  },
  {
    id: "138",
    type: Type.normal,
    name: "Amonita",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "138_r",
    type: Type.reverse,
    name: "Amonita",
    rarity: Rarity.peuCommune,
  },
  {
    id: "139",
    type: Type.normal,
    name: "Amonistar",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "139_r",
    type: Type.reverse,
    name: "Amonistar",
    rarity: Rarity.rare,
  },
  {
    id: "140",
    type: Type.normal,
    name: "Kabuto",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "140_r",
    type: Type.reverse,
    name: "Kabuto",
    rarity: Rarity.peuCommune,
  },
  {
    id: "141",
    type: Type.normal,
    name: "Kabutops",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "141_r",
    type: Type.reverse,
    name: "Kabutops",
    rarity: Rarity.rare,
  },
  {
    id: "142",
    type: Type.normal,
    name: "Ptéra",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "142_r",
    type: Type.reverse,
    name: "Ptéra",
    rarity: Rarity.rare,
  },
  {
    id: "143",
    type: Type.normal,
    name: "Ronflex",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "143_r",
    type: Type.reverse,
    name: "Ronflex",
    rarity: Rarity.peuCommune,
  },
  {
    id: "144",
    type: Type.normal,
    name: "Artikodin",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "144_r",
    type: Type.reverse,
    name: "Artikodin",
    rarity: Rarity.rare,
  },
  {
    id: "145",
    type: Type.holo,
    name: "Électhor-ex",
    rarity: Rarity.doubleRare,
  },
  {
    id: "146",
    type: Type.normal,
    name: "Sulfura",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "146_r",
    type: Type.reverse,
    name: "Sulfura",
    rarity: Rarity.rare,
  },
  {
    id: "147",
    type: Type.normal,
    name: "Minidraco",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "147_r",
    type: Type.reverse,
    name: "Minidraco",
    rarity: Rarity.commune,
  },
  {
    id: "148",
    type: Type.normal,
    name: "Draco",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "148_r",
    type: Type.reverse,
    name: "Draco",
    rarity: Rarity.peuCommune,
  },
  {
    id: "149",
    type: Type.normal,
    name: "Dracolosse",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "149_r",
    type: Type.reverse,
    name: "Dracolosse",
    rarity: Rarity.rare,
  },
  {
    id: "150",
    type: Type.normal,
    name: "Mewtwo",
    rarity: Rarity.rare,
    hasReverseVersion: true,
  },
  {
    id: "150_r",
    type: Type.reverse,
    name: "Mewtwo",
    rarity: Rarity.rare,
  },
  {
    id: "151",
    type: Type.holo,
    name: "Mew-ex",
    rarity: Rarity.doubleRare,
  },
  {
    id: "152",
    type: Type.normal,
    name: "Fossile Dôme Ancien",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "152_r",
    type: Type.reverse,
    name: "Fossile Dôme Ancien",
    rarity: Rarity.commune,
  },
  {
    id: "153",
    type: Type.normal,
    name: "Fossile Nautile Ancien",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "153_r",
    type: Type.reverse,
    name: "Fossile Nautile Ancien",
    rarity: Rarity.commune,
  },
  {
    id: "154",
    type: Type.normal,
    name: "Vieil Ambre Ancien",
    rarity: Rarity.commune,
    hasReverseVersion: true,
  },
  {
    id: "154_r",
    type: Type.reverse,
    name: "Vieil Ambre Ancien",
    rarity: Rarity.commune,
  },
  {
    id: "155",
    type: Type.normal,
    name: "Gros Ballon",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "155_r",
    type: Type.reverse,
    name: "Gros Ballon",
    rarity: Rarity.peuCommune,
  },
  {
    id: "156",
    type: Type.normal,
    name: "Transfert de Léo",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "156_r",
    type: Type.reverse,
    name: "Transfert de Léo",
    rarity: Rarity.peuCommune,
  },
  {
    id: "157",
    type: Type.normal,
    name: "Piste Cyclable",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "157_r",
    type: Type.reverse,
    name: "Piste Cyclable",
    rarity: Rarity.peuCommune,
  },
  {
    id: "158",
    type: Type.normal,
    name: "Aide de Nina",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "158_r",
    type: Type.reverse,
    name: "Aide de Nina",
    rarity: Rarity.peuCommune,
  },
  {
    id: "159",
    type: Type.normal,
    name: "Stickers Énergie",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "159_r",
    type: Type.reverse,
    name: "Stickers Énergie",
    rarity: Rarity.peuCommune,
  },
  {
    id: "160",
    type: Type.normal,
    name: "Invitation d’Erika",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "160_r",
    type: Type.reverse,
    name: "Invitation d’Erika",
    rarity: Rarity.peuCommune,
  },
  {
    id: "161",
    type: Type.normal,
    name: "Charisme de Giovanni",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "161_r",
    type: Type.reverse,
    name: "Charisme de Giovanni",
    rarity: Rarity.peuCommune,
  },
  {
    id: "162",
    type: Type.normal,
    name: "Pince Attrapeuse",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "162_r",
    type: Type.reverse,
    name: "Pince Attrapeuse",
    rarity: Rarity.peuCommune,
  },
  {
    id: "163",
    type: Type.normal,
    name: "Restes",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "163_r",
    type: Type.reverse,
    name: "Restes",
    rarity: Rarity.peuCommune,
  },
  {
    id: "164",
    type: Type.normal,
    name: "Lunettes de Protection",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "164_r",
    type: Type.reverse,
    name: "Lunettes de Protection",
    rarity: Rarity.peuCommune,
  },
  {
    id: "165",
    type: Type.normal,
    name: "Bandeau Rigide",
    rarity: Rarity.peuCommune,
    hasReverseVersion: true,
  },
  {
    id: "165_r",
    type: Type.reverse,
    name: "Bandeau Rigide",
    rarity: Rarity.peuCommune,
  },
  {
    id: "166",
    type: Type.secret,
    name: "Bulbizarre",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "167",
    type: Type.secret,
    name: "Herbizarre",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "168",
    type: Type.secret,
    name: "Salamèche",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "169",
    type: Type.secret,
    name: "Reptincel",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "170",
    type: Type.secret,
    name: "Carapuce",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "171",
    type: Type.secret,
    name: "Carabaffe",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "172",
    type: Type.secret,
    name: "Chenipan",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "173",
    type: Type.secret,
    name: "Pikachu",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "174",
    type: Type.secret,
    name: "Nidoking",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "175",
    type: Type.secret,
    name: "Psykokwak",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "176",
    type: Type.secret,
    name: "Têtarte",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "177",
    type: Type.secret,
    name: "Machopeur",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "178",
    type: Type.secret,
    name: "Saquedeneu",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "179",
    type: Type.secret,
    name: "M. Mime",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "180",
    type: Type.secret,
    name: "Amonita",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "181",
    type: Type.secret,
    name: "Draco",
    rarity: Rarity.illustrationRare,
  },
  {
    id: "182",
    type: Type.secret,
    name: "Florizarre-ex",
    rarity: Rarity.ultraRare,
  },
  {
    id: "183",
    type: Type.secret,
    name: "Dracaufeu-ex",
    rarity: Rarity.ultraRare,
  },
  {
    id: "184",
    type: Type.secret,
    name: "Tortank-ex",
    rarity: Rarity.ultraRare,
  },
  {
    id: "185",
    type: Type.secret,
    name: "Arbok-ex",
    rarity: Rarity.ultraRare,
  },
  {
    id: "186",
    type: Type.secret,
    name: "Feunard-ex",
    rarity: Rarity.ultraRare,
  },
  {
    id: "187",
    type: Type.secret,
    name: "Grodoudou-ex",
    rarity: Rarity.ultraRare,
  },
  {
    id: "188",
    type: Type.secret,
    name: "Alakazam-ex",
    rarity: Rarity.ultraRare,
  },
  {
    id: "189",
    type: Type.secret,
    name: "Grolem-ex",
    rarity: Rarity.ultraRare,
  },
  {
    id: "190",
    type: Type.secret,
    name: "Kangourex-ex",
    rarity: Rarity.ultraRare,
  },
  {
    id: "191",
    type: Type.secret,
    name: "Lippoutou-ex",
    rarity: Rarity.ultraRare,
  },
  {
    id: "192",
    type: Type.secret,
    name: "Électhor-ex",
    rarity: Rarity.ultraRare,
  },
  {
    id: "193",
    type: Type.secret,
    name: "Mew-ex",
    rarity: Rarity.ultraRare,
  },
  {
    id: "194",
    type: Type.secret,
    name: "Transfert de Léo",
    rarity: Rarity.ultraRare,
  },
  {
    id: "195",
    type: Type.secret,
    name: "Aide de Nina",
    rarity: Rarity.ultraRare,
  },
  {
    id: "196",
    type: Type.secret,
    name: "Invitation d’Erika",
    rarity: Rarity.ultraRare,
  },
  {
    id: "197",
    type: Type.secret,
    name: "Charisme de Giovanni",
    rarity: Rarity.ultraRare,
  },
  {
    id: "198",
    type: Type.secret,
    name: "Florizarre-ex",
    rarity: Rarity.illustrationSpecialeRare,
  },
  {
    id: "199",
    type: Type.secret,
    name: "Dracaufeu-ex",
    rarity: Rarity.illustrationSpecialeRare,
  },
  {
    id: "200",
    type: Type.secret,
    name: "Tortank-ex",
    rarity: Rarity.illustrationSpecialeRare,
  },
  {
    id: "201",
    type: Type.secret,
    name: "Alakazam-ex",
    rarity: Rarity.illustrationSpecialeRare,
  },
  {
    id: "202",
    type: Type.secret,
    name: "Électhor-ex",
    rarity: Rarity.illustrationSpecialeRare,
  },
  {
    id: "203",
    type: Type.secret,
    name: "Invitation d’Erika",
    rarity: Rarity.illustrationSpecialeRare,
  },
  {
    id: "204",
    type: Type.secret,
    name: "Charisme de Giovanni",
    rarity: Rarity.illustrationSpecialeRare,
  },
  {
    id: "205",
    type: Type.secret,
    name: "Mew ex",
    rarity: Rarity.hyperRare,
  },
  {
    id: "206",
    type: Type.secret,
    name: "Échange",
    rarity: Rarity.hyperRare,
  },
  {
    id: "207",
    type: Type.secret,
    name: "Énergie Psy de base",
    rarity: Rarity.hyperRare,
  },
];
